CRUD_Pessoa/Models/PessoaFisicaModel.cs
using System;
using System.Data.Entity;

namespace CRUD_Pessoa.Models
{
    public class PessoaFisicaModel
    {
        public int ID { get; set; }
        public string NomeCompleto { get; set; }

        public DateTime DataNascimento { get; set; }
        public string ValorRenda { get; set; }
        public string CPF { get; set; }
    }

    public class PessoaDBContext : DbContext
    {
        public DbSet<PessoaFisicaModel> Pessoas { get; set; }
    }
}

CRUD_Pessoa/Controllers/PessoaFisicaController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CRUD_Pessoa.Models;

namespace CRUD_Pessoa.Controllers
{
    public class PessoaFisicaController : Controller
    {
        private PessoaDBContext db = new PessoaDBContext();

        // GET: PessoaFisica
        public ActionResult Index()
        {
            return View(db.Pessoas.ToList());
        }

        // GET: PessoaFisica/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PessoaFisicaModel pessoaFisicaModel = db.Pessoas.Find(id);
            if (pessoaFisicaModel == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFisicaModel);
        }

        // GET: PessoaFisica/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PessoaFisica/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NomeCompleto,DataNascimento,ValorRenda,CPF")] PessoaFisicaModel pessoaFisicaModel)
        {
            if (ModelState.IsValid)
            {
                if (ValidarCPF(pessoaFisicaModel.CPF))
                {
                    db.Pessoas.Add(pessoaFisicaModel);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("CPF", "CPF inválido. Por favor, insira um CPF válido.");
                    return View();
                }
            }
            return View(pessoaFisicaModel);
        }

        // GET: PessoaFisica/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PessoaFisicaModel pessoaFisicaModel = db.Pessoas.Find(id);
            if (pessoaFisicaModel == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFisicaModel);
        }

        // POST: PessoaFisica/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NomeCompleto,DataNascimento,ValorRenda,CPF")] PessoaFisicaModel pessoaFisicaModel)
        {
            if (ModelState.IsValid)
            {
                if (ValidarCPF(pessoaFisicaModel.CPF))
                {
                    db.Entry(pessoaFisicaModel).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("CPF", "CPF inválido. Por favor, insira um CPF válido.");
                    return View();
                }                
            }
            return View(pessoaFisicaModel);
        }

        // GET: PessoaFisica/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PessoaFisicaModel pessoaFisicaModel = db.Pessoas.Find(id);
            if (pessoaFisicaModel == null)
            {
                return HttpNotFound();
            }
            return View(pessoaFisicaModel);
        }

        // POST: PessoaFisica/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PessoaFisicaModel pessoaFisicaModel = db.Pessoas.Find(id);
            db.Pessoas.Remove(pessoaFisicaModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Metodo para verificar se todos os dígitos do CPF são iguais
        public static bool ValidarCPF(string cpf)
        {
            // Remover caracteres não numéricos
            cpf = cpf.Replace(".", "").Replace("-", "");

            // Verificar se todos os dígitos do CPF são iguais
            if (cpf.Distinct().Count() == 1)
            {
                return false;
            }

            return true;
        }

    }
}

CRUD_Pessoa/Views/PessoaFisica/Create.cshtml
@model CRUD_Pessoa.Models.PessoaFisicaModel

@{
    ViewBag.Title = "Cadastro";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Cadastro de Pessoa</title>
    <link href="~/Scripts/PessoaStyle.css" rel="stylesheet" />
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <h2>Criar um novo perfil</h2>
            <hr />
            <div style="padding-left: 5%">
                <div class="form-group" style="margin-top: 50px">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.LabelFor(model => model.NomeCompleto, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="nomeCompleto" name="nomeCompleto">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.NomeCompleto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="dataNascimento" name="DataNascimento">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.LabelFor(model => model.ValorRenda, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="valor" name="ValorRenda">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.ValorRenda, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="cpf" name="CPF">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="botao-bottom">
                <div class="form-group">
                    <div class="row g-3 align-items-center" style="padding-left: 5%">
                        <div class="col-auto">
                            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary btn-edit" })
                        </div>
                        <div class="col-auto">
                            <input type="submit" value="Salvar" class="btn btn-success btn-edit" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js")
        @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js")
        @Scripts.Render("~/Scripts/site.js")
    }
</body>
</html>

CRUD_Pessoa/Views/PessoaFisica/Delete.cshtml
@model CRUD_Pessoa.Models.PessoaFisicaModel

@{
    ViewBag.Title = "Excluir";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de excluir o perfil</title>
    <link href="~/Scripts/PessoaStyle.css" rel="stylesheet" />
</head>
<body>
    <div>
        @Html.AntiForgeryToken()
        <div>
            <h2>Excluir</h2>
            <hr />
            <h5>Tem certeza de que deseja excluir isto?</h5>
            <br />
            <div class="topoTabela">
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2 linha-excluir">
                            @Html.DisplayNameFor(model => model.NomeCompleto)
                        </div>
                        <div class="col-auto linha-excluir">
                            @Html.DisplayFor(model => model.NomeCompleto)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2 linha-excluir">
                            @Html.DisplayNameFor(model => model.DataNascimento)
                        </div>
                        <div class="col-auto linha-excluir">
                            @if (@Model.DataNascimento != null)
                            {
                                @Model.DataNascimento.ToString("dd/MM/yyyy")
                            }
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2 linha-excluir">
                            @Html.DisplayNameFor(model => model.ValorRenda)
                        </div>
                        <div class="col-auto linha-excluir">
                            @Html.DisplayFor(model => model.ValorRenda)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2 linha-excluir">
                            @Html.DisplayNameFor(model => model.CPF)
                        </div>
                        <div class="col-auto linha-excluir">
                            @Html.DisplayFor(model => model.CPF)
                        </div>
                    </div>
                </div>
            </div>
            <div class="botao-bottom">
                @using (Html.BeginForm("Delete", "PessoaFisica", new { id = Model.ID }, FormMethod.Post, new { onsubmit = "return confirmExclusao();" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <div class="row g-3 align-items-center" style="padding-left: 5%">
                            <div class="col-auto">
                                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary btn-edit" })
                            </div>
                            <div class="col-auto">
                                <input type="submit" value="Excluir" class="btn btn-danger btn-edit" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    @section Scripts {
        <script src="~/Scripts/site.js"></script>
    }
</body>
</html>

CRUD_Pessoa/Views/PessoaFisica/Details.cshtml
@model CRUD_Pessoa.Models.PessoaFisicaModel

@{
    ViewBag.Title = "Detalhes Da Pessoa Física";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página De Detalhes Da Pessoa Física</title>
    <link href="~/Scripts/PessoaStyle.css" rel="stylesheet" />
</head>
<body>
    <div>
        @Html.AntiForgeryToken()
        <div>
            <h2>Detalhes</h2>
            <hr />
            <div class="topoTabela">
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.DisplayNameFor(model => model.NomeCompleto)
                        </div>
                        <div class="col-auto">
                            <input type="text" id="nomeCompleto" name="nomeCompleto" value="@Model.NomeCompleto" disabled>
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.NomeCompleto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="dataNascimento" name="DataNascimento" value="@Model.DataNascimento" disabled>
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.DisplayNameFor(model => model.ValorRenda)
                        </div>
                        <div class="col-auto">
                            <input type="text" id="valorRenda" name="ValorRenda" value="@Model.ValorRenda" disabled>
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.ValorRenda, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                            @Html.DisplayNameFor(model => model.CPF)
                        </div>
                        <div class="col-auto">
                            <input type="text" id="cpf" name="CPF" value="@Model.CPF" disabled>
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="botao-bottom">
            <div class="form-group">
                @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary btn-edit" })
            </div>
        </div>
    </div>
</body>
</html>

CRUD_Pessoa/Views/PessoaFisica/Edit.cshtml
@model CRUD_Pessoa.Models.PessoaFisicaModel

@{
    ViewBag.Title = "Alterar";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página para alterar o perfil</title>
    <link href="~/Scripts/PessoaStyle.css" rel="stylesheet" />
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h2>Alterar o perfil</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            <div style="padding-left: 5%">
                <div class="form-group" style="margin-top: 50px">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                                @Html.LabelFor(model => model.NomeCompleto, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="nomeCompleto" name="nomeCompleto" value="@Model.NomeCompleto">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.NomeCompleto, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                                @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="dataNascimento" name="DataNascimento" value="@Model.DataNascimento">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                                @Html.LabelFor(model => model.ValorRenda, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="valor" name="ValorRenda" value="@Model.ValorRenda">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.ValorRenda, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row g-3 align-items-center">
                        <div class="col-2">
                                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
                        </div>
                        <div class="col-auto">
                            <input type="text" id="cpf" name="CPF" value="@Model.CPF">
                            <span class="highlight"></span>
                            <span class="bar"></span>
                        </div>
                        <div class="col-auto">
                            @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="botao-bottom">
                <div class="form-group">
                    <div class="row g-3 align-items-center" style="padding-left: 5%">
                        <div class="col-auto">
                            @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-primary btn-edit" })
                        </div>
                        <div class="col-auto">
                            <input type="submit" value="Salvar" class="btn btn-success btn-edit" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</body>
</html>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js")
    @Scripts.Render("https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js")
    @Scripts.Render("~/Scripts/site.js")
}

CRUD_Pessoa/Views/PessoaFisica/Index.cshtml
@model IEnumerable<CRUD_Pessoa.Models.PessoaFisicaModel>

@{
    ViewBag.Title = "Principal";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Principal</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="~/Scripts/PessoaStyle.css" rel="stylesheet" />
</head>
<body>

    <p>
        @Html.ActionLink("Criar Novo Perfil", "Create", null, new { @class = "btn btn-primary btn-edit" })
    </p>
    <div>
        <div class="tabela-scroll">
            <table class="table table-hover">
                <tr class="table-active  tabela-cabecalho">
                    <th style="text-align: center;">
                        @Html.DisplayNameFor(model => model.NomeCompleto)
                    </th>
                    <th style="text-align: center;">
                        @Html.DisplayNameFor(model => model.DataNascimento)
                    </th>
                    <th style="text-align: center;">
                        @Html.DisplayNameFor(model => model.ValorRenda)
                    </th>
                    <th style="text-align: center;">
                        @Html.DisplayNameFor(model => model.CPF)
                    </th>
                    <th>&nbsp;</th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="linhasDaTabelaPrincipal">
                            @Html.DisplayFor(modelItem => item.NomeCompleto)
                        </td>
                        <td class="linhasDaTabelaPrincipal">
                            @if (item.DataNascimento != null)
                            {
                                @item.DataNascimento.ToString("dd/MM/yyyy")
                            }
                        </td>
                        <td class="linhasDaTabelaPrincipal">
                            @Html.DisplayFor(modelItem => item.ValorRenda)
                        </td>
                        <td class="linhasDaTabelaPrincipal">
                            @Html.DisplayFor(modelItem => item.CPF)
                        </td>
                        <td>
                            <a href="/PessoaFisica/Edit/@item.ID" class="links btn btn-primary">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <a href="/PessoaFisica/Details/@item.ID" class="links btn btn-primary">
                                <i class="fa fa-search"></i>
                            </a>
                            <a href="/PessoaFisica/Delete/@item.ID" class="links btn btn-primary fixed-trash">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

    @section Scripts {
        @Scripts.Render("~/Scripts/site.js")
    }
</body>
</html>

CRUD_Pessoa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Pessoa Fisica - CRUD", "Index", "PessoaFisica", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar a navegação" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>